services:
  postgres:
    image: bitnami/postgresql:17.6.0
    container_name: ${POSTGRES_CONTAINER_NAME}
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./.bd_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
